dist: trusty
sudo: required
language: nix
notifications:
  email: false
script:
  - nix-shell --run "make test"
after_success:
  - test -n $TRAVIS_TAG && (echo $GITHUB_TOKEN | pulp login) && (yes | pulp publish --no-push)
