name: Check

on:
  pull_request:
  push:
    branches:
      - main
      - "v[0-9]*.[0-9]*.x"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install environment
        run: nix-shell

      - name: Build
        run: nix-shell --run "build test"

      - name: Test
        run: nix-shell --run check-code

      - name: Verify Pulp + Bower
        run: nix-shell --run check-pulp

  Validate_Format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Install environment
        run: nix-shell

      - name: Validate Format
        run: nix-shell --run check-format
