name: Check

on:
  pull_request:
  push:
    branches:
      - master
      - 'v[0-9]*.[0-9]*.x'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Build
        run: nix-shell --run build

      - name: Test
        run: nix-shell --run check-code

  Validate_Format:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Validate Format
        run: nix-shell --run check-format
