name: Check

on:
  pull_request:
  push:
    branches:
      - master
      - 'v[0-9]*.[0-9]*.x'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Build
        run: nix-shell --run 'make build'

      - name: Test
        run: nix-shell --run 'make test-code'

  Validate_Format:
    runs-on: ubuntu-latest
    steps:

      - name: Check out codebase
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Validate Format
        run: nix-shell --run 'make test-format'
